### PR TITLE
Extend speed range (0.05x - 4x)

### PR DESCRIPTION
**Pull request by lawdalana**
I just extend the speed range.

### CODE REVIEW

**Comment by lukkiddd** [comment]
Hello @lawdalana is it too much options?

Should we just limit to 0.5x, 1x, 1.5x, 2x, 3x, 4x?

2.3x, 2.4x, etc. I think it is rarely to be use.

**Comment by lawdalana** [comment]
More is better than less.

**Comment by lawdalana** [comment]
> Hello @lawdalana is it too much options?
> 
> Should we just limit to 0.5x, 0.75x, 1x, 1.25x, 1.5x, 2x, 3x, 4x?
> 
> 2.3x, 2.4x, etc. I think it is rarely to be use.

 More is better than less.

**Comment by RemLampa** [comment]
@lawdalana Thanks for taking the time to do this! Appreciate it. :heart_eyes: 

But I'd have to agree with @lukkiddd. The increments are too fine grained that the difference 0.1 vs. 0.2, for example, is barely noticeable. :sweat_smile:  I like his suggestion of increasing intervals as you go further up or down the scale. Could you go with that instead?

Again, thanks for your help. Will await for the changes. :wink:

**Comment by lawdalana** [comment]
> @lawdalana Thanks for taking the time to do this! Appreciate it. 😍
> 
> But I'd have to agree with @lukkiddd. The increments are too fine grained that the difference 0.1 vs. 0.2, for example, is barely noticeable. 😅 I like his suggestion of increasing intervals as you go further up or down the scale. Could you go with that instead?
> 
> Again, thanks for your help. Will await for the changes. 😉

🤣 I reduce the scale already.

**Review by RemLampa — APPROVED** [review]

**Comment by RemLampa** [comment]
@lawdalana Awesome! Releasing this. Thanks!

**Comment by lawdalana** [comment]
@RemLampa Please approve again. I forgot to register my GPG keys.

**Review by RemLampa — APPROVED** [review]
Awesome! Thanks so much!

**Pull request merged**
